config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  authenticated :user do
    root "pages#home", as: "authenticated_root"
  end
  devise_scope :user do
    root "devise/sessions#new"
  end
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "orders#index"
end

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
    aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-between" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <div class="mr-auto mt-2 mt-lg-0 px-3">
        <%= link_to 'Yalla Notlob', root_path, class:"navbar-brand" %>
      </div>
      <%# <li class="nav-item"><%= link_to 'Friends', friends_path, class:"nav-link" </li> %>
      <%# <li class="nav-item"><%= link_to 'Groups', groups_path, class:"nav-link" </li> %>
      <li class="nav-item">
        <%= link_to "Orders", orders_path, class:"nav-link" %>
      </li>
      <%# <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Add Order", new_order_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%# <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%# <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
      </li>
      <%# <% else %>
      <li class="nav-item">
        <%# <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%# <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      </li>
      <%# <% end %>
    </ul>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Yalla-Notlob</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <br />
    <%# <%= 'Welcome ' + current_user.first_name if user_signed_in? %>
    <br />
    <% if notice %></p>
    <%= render 'layouts/alerts' %>
    <% end %>
    </br>
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous">
  </script>

</body>

</html>